# Site settings
name: Sumit Kumar
title: Sumit Kumar | Machine Learning Researcher
description: For the past few years, I have been motivated by the following question, What are the powers of data-driven approaches in multidisciplinary domains? This question led to independent lines of work that include optimizing algorithms and applying deep learning methods to solve research problems for healthcare analytics and social network analysis. 
url: http://sumit6597.github.io/
baseurl: ""
email: sumit.atlancey@gmail.com
cover: http://sumit6597.github.io/img/og.jpg
logo: http://sumit6597.github.io/img/logo-black.png

resume: https://drive.google.com/file/d/16Kwo3heITXKWtLS3es4kF1Rsnar38_Cy/view?usp=sharing
google_verify: 22x1tQ2NU74XPFxGdy0ApDyU1yxKPU5iymeIeO-roUU

resume: http://ambityga.github.io/resume
social:
  - title: email
    url: mailto:ambesh.sinha@gmail.com
#  - title: twitter
#    url: https://twitter.com/bchiang7
#  - title: instagram
#    url: https://instagram.com/bchiang7
#  - title: codepen
#    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/AmbiTyga
  - title: linkedin
    url: https://www.linkedin.com/in/ambesh-shekhar-1a115414b/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
