# Site settings
name: Sumit Kumar
title: Sumit Kumar | Homepage
description: Portfolio page of Sumit Kumar
url: http://sumit6597.github.io/
baseurl: ""
email: sumit.atlancey@gmail.com
cover: http://sumit6597.github.io/img/og.jpg
logo: http://sumit6597.github.io/img/logo-black.png



resume:  
social:
  - title: email
    url: mailto:sumit.atlancey@gmail.com
  - title: twitter
    url: https://twitter.com/Sumit6597
 # - title: instagram
  #  url: https://instagram.com/sumit__west
#  - title: codepen
#    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/sumit6597
  - title: linkedin
    url: https://www.linkedin.com/in/sumit-kumar6597/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
