- row: row1
  services:
    - heading: Academics
      sprite: webdev
      text: Pursuing my bachelor's engineering from Birla Institute of Technology, Mesra. Solving research problem that is not bounded only to academics.

    - heading: NLP and Data Science
      sprite: ui
      text: I am generally interested in optimization and deep learning.I am particularly excited about the interplay between social media and machine learning. My work has been applied to learning dynamical systems in sustainability, health, and making robust learning models.
- row: row2
  services:
    - heading: Programmer 
      sprite: xd
      text: I practice my coding on various platforms and compete with my friends. I use this quirk to help others by guiding them or helping them in their work.

    - heading: Secretary
      sprite: wit
      text: I am the secretary, technical support and one of the people who established the <strong>Technical Club at Birla Institute of Technology</strong> aiming to provide a platform for students intrigued by the concepts of machine learning  and IoT and to make them aware of the current working ambience in this field by encouraging them to take part in different competitions and research.
