


- row: row1
  services:
    - heading: Academics
      sprite: webdev
      text: <ul><h4>Last 2 semesters</h4> <li>Soft Computing <li>Data Mining and Warehousing<li>Distributed and Paralllel Systems<li>Cryptography and Network Security<Business Ethics></ul>

    - heading: NLP and Data Science
      sprite: ui
      text: I am generally interested in optimization and deep learning. I am particularly excited about text summarization, text generation in NLP. My work has been applied to learning dynamical systems in sustainability, social media analysis, low resource language and making robust learning models.
- row: row2
  services:
    - heading: Extracurricular 
      sprite: xd
      text:  Paper presentation at 34th NeurIPS 2020, ACM- 8th CODS & 26th COMAD 2021, CMU IdeaS conferences, and 17th ICON 2020.<ul><li>Black Lives Matter Twitter dataset:<br><a href="https://doi.org/10.5281/zenodo.4000539"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.4000539.svg" alt="DOI"></a></ul>


    - heading: Awards & Achievement
      sprite: wit
      text: <p><ul><li>Selected for the ”InSc Young Researcher Award”<li>Received NeurIPS 2020 grant support for MLPH workshop <li> Grant for visiting scholar at Jean Monnet University, Lyon</ul></p>
           
