- row: row1
  services:
    - heading: Academics
      sprite: webdev
      text: Senior year B.E student from Birla Institute of Technology, Mesra.

    - heading: NLP and Data Science
      sprite: ui
      text: I am generally interested in optimization and deep learning.> I am particularly excited about text summarization, text generation in NLP. My work has been applied to learning dynamical systems in sustainability, health, and making robust learning models.
- row: row2
  services:
    - heading: Extracurricular 
      sprite: xd
      text: Workshop paper presentation in NeurIPS 2020, CODS COMAD 21, CMU IdeaS conferences e.t.c.

    - heading: Awards & Achievement
      sprite: wit
      text: 1) Selected for the title ”InSc Young Researcher Award” 
            2) Received NeurIPS 2020 registration grant support for presentation in MLPH workshop 
            3) Entitled scholarship grant for visiting scholar at Jean Monnet University, Lyon, France
           
