


- row: row1
  services:
    - heading: Academics
      sprite: webdev
      text: Senior year B.E student from Birla Institute of Technology, Mesra.

    - heading: NLP and Data Science
      sprite: ui
      text: I am generally interested in optimization and deep learning. I am particularly excited about text summarization, text generation in NLP. My work has been applied to learning dynamical systems in sustainability, health, and making robust learning models.
- row: row2
  services:
    - heading: Extracurricular 
      sprite: xd
      text: Workshop paper presentation in NeurIPS 2020, CODS COMAD 21, IdeaS conferences and ICON 2020. <p>BLM hatespeech dataset:<a href="https://doi.org/10.5281/zenodo.4000398"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.4000398.svg" alt="DOI"></a></p>


    - heading: Awards & Achievement
      sprite: wit
      text: <p class="test"> 1. Selected for the title ”InSc Young Researcher Award” <br>2. Received NeurIPS 2020 grant support for MLPH workshop 
            <br> 3. Entitled grant for visiting scholar at Jean Monnet University, Lyon, France</p>
           
